# Generated by Django 2.1.7 on 2019-10-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='news',
            new_name='stories',
        ),
    ]
