# Generated by Django 2.1.7 on 2019-10-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_stories_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='priority',
            field=models.IntegerField(choices=[(1, '第一级'), (2, '第二级'), (3, '第三级')], help_text='优先级', verbose_name='优先级'),
        ),
    ]
