# Generated by Django 2.1.7 on 2019-10-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20191024_1752'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='announcement',
            table='tb_announcement',
        ),
    ]
